### ISSUE TITLE
A problem with deploying in Netlify 

### ISSUE THREAD

**Issue by stardoom4** [paulmartins/hugo-digital-garden-theme#14]
I deployed a fork of this theme in Netlify but in the site nothing was there it was Empty only 2023 was visible in the bottom and menu button with theme changing button was visible. How can I fix it.
[Deploy can be found here](https://isro2.netlify.app)

**Comment by paulmartins** [comment]
Please take a look at point 3. in the [README](https://github.com/paulmartins/hugo-digital-garden-theme#getting-started). It says you should customise your site in `config.toml`, with a link to an example. If you just fork and deploy that will not work, you'd still need to manually setup your `config.toml` with your info.  
Let me know if this fixes your issue so I can close this issue.

**Comment by stardoom4** [comment]
I changed the config.toml but the deploy is still the same.
[Here is the deploy ](https://celestialminds.netlify.app/)

**Comment by paulmartins** [comment]
Could you paste the link to your config.toml ?  
As I assume your deploy is done from the main branch I cannot see the file updates you mentioned.
Is this the one: https://github.com/stardoom4/hugo-digital-garden-theme/blob/main/config.toml ?

**Comment by stardoom4** [comment]
Like this 
[Config.toml](https://github.com/stardoom4/hugo-digital-garden-theme/blob/4e3a59646ab37563262ba59ffb737c30b300f39d/config.toml) 
Do I have to put it in examplesite directory.

**Comment by paulmartins** [comment]
That looks better. 

You should not put it in exampleSite directory. This folder is just an example you can browse to see how it works. It corresponds to the [demo site](https://hugo-digital-garden-demo.netlify.app/) if I remember well. 

You should only update the folders on the root of the repo. 
You also probably want to create a `content/` folder in the root of the repo where you can organise your articles (using a similar structure as in exampleSite)

**Comment by stardoom4** [comment]
I am getting this error at deployment

4:18:23 PM: Error: module hugo-digital-garden-theme not found; either add it as a Hugo Module or store it in /opt/build/repo/themes.: module does not exist

**Comment by paulmartins** [comment]
It looks like the theme was not installed (ie the theme should be inside the `themes/` directory or your website.

Just to be clear, the repo is a **theme** for a hugo website. **It is not a website**, so it should be installed as a theme to an existing site.

Please follow the instructions in the [README](https://github.com/stardoom4/hugo-digital-garden-theme/tree/main#getting-started) to first quickstart a hugo website, and then install the theme.

**Comment by stardoom4** [comment]
Okay , now I get my mistake. Thanks for the Help.
