### ISSUE TITLE
Additional features 

### ISSUE THREAD

**Issue by Ritesh1137** [paulmartins/hugo-digital-garden-theme#15]
Hey Paul, 
I really like your digital garden theme and how it's structured. I wanted to add some additional features to this repo, inspired from this other [Jekyll-based digital garden theme.](https://github.com/maximevaillancourt/digital-garden-jekyll-template). Specifically:

**_Primary additions_**
- **creating Roam-style double bracket link syntax to other notes**
- **creating backlinks to other notes automatically** 
- **displaying notes that mention current notes**

**_Secondary additions_**

- Including graph visualization of the notes and their links
- Featuring link previews on hover 

By automating the generation of backlinks to a note from other notes that mention it, here are some benefits:
- Contextual Understanding
- Navigational Ease
- Discovering Relationships
- Knowledge Management
- Encouraging Exploration within notes

I would like to hear your thoughts on this.

**Comment by paulmartins** [comment]
Hi Ritesh,
I'm glad you like the template. 
By all means feel free to fork the repo and submit a PR when ready. 
Those are all great ideas that will improve the template :) 

Yours,
Paul
