### ISSUE TITLE
Allow easy linking to headers in content posts

### ISSUE THREAD

**Issue by james-s-w-clark** [paulmartins/hugo-digital-garden-theme#7]
Is it possible to add this feature, or does it exist and I'm just not using Hugo correctly?

For my page https://idiosapps.github.io/garden/equalisers-and-pdfs, I'd like to go directly to a header via a slug in the url, e.g. https://idiosapps.github.io/garden/equalisers-and-pdfs/#creating-a-parametric-eq-for-peace-/-equaliser-apo. I'd also like to be able to copy the slug to the clipboard with an link-icon (or hash) appearing when I hover over the header.

---

# Example from another site

Here's an example with the Doks theme:

https://doks.netlify.app/docs/prologue/introduction/#get-started

![image](https://user-images.githubusercontent.com/12559216/184504110-f94bfd27-6a49-4897-adcd-edb651bce640.png)

**Comment by paulmartins** [comment]
This was implemented as part of #16 

Sorry again for the delay, please update your theme version and enjoy the new linked headers !
